# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Official Homepage of Lars Wathney
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the homepage of Lars I. Wathney, writer of horror, and weird fiction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wathney.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

# Compress CSS
sass:
  sass_dir: _sass
  style: compressed

#Compress HTML options
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
